services:
  - type: web
    name: cryonix-booking-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: JWT_EXPIRES_IN
        value: 7d
